services:
  postgres:
   image: postgres
   container_name: postgres
   restart: unless-stopped
   ports:
     - 5432:5432
   environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}

  app:
    image: party-web-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__TimescaleConnection=Host=postgres:5432;Database=${POSTGRES_DB};Username=postgres;Password=${POSTGRES_PASSWORD};
    ports:
      - 5259:8080
